package com.espace.astro.single;

import com.espace.Dot;

public class AstronomicalObject extends Dot{
	
	/**
	 * 
	 * @param name Имя АОбъекта - Уникальное поле класса
	 * 
	 * @param history История АОбъекта - Уникальное поле класса
	 * 
	 * @param age Возраст АОбъекта - Уникальное поле класса
	 * 
	 * @param weight Вес АОбъекта - Уникальное поле класса
	 * 
	 * @param width Ширина АОбъекта - Уникальное поле класса
	 * 
	 * @param height Высота АОбъекта - Уникальное поле класса
	 * 
	 * @param x Положение АОбъекта по x
	 * 
	 * @param y Положение АОбъекта по y
	 */
	
	public AstronomicalObject(String name, String[] history,
			double age, double weight,
			int width, int height, int x, int y) {
		super(x, y);
		
		//Присваивание от конструктора к полям класса
		this.name = name;
		this.history = history;
		this.weight = weight;
		this.age = age;
	}
	
	//Get&Set generated by eclipse
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String[] getHistory() {
		return history;
	}
	public void setHistory(String[] history) {
		this.history = history;
	}
	public double getAge() {
		return age;
	}
	public void setAge(double age) {
		this.age = age;
	}
	public double getWeight() {
		return weight;
	}
	public void setWeight(double weight) {
		this.weight = weight;
	}
	public int getWidth() {
		return width;
	}
	public void setWidth(int width) {
		this.width = width;
	}
	public int getHeight() {
		return height;
	}
	public void setHeight(int height) {
		this.height = height;
	}
	
	//Поля класса
	private String name;
	private String[] history;
	
	private double age;
	private double weight;
	
	private int width;
	private int height;
}
