package com.espace.astro.single;

public class Planet extends AstronomicalObject{
	
	/**
	 * 
	 * @param name Название планеты
	 * 
	 * @param history История планеты
	 * 
	 * @param weight Вес планеты - Уникальное поле
	 * 
	 * @param age Возраст планеты - Уникальное поле
	 * 
	 * @param radius Радиус планеты (так-же её высота&ширина) - Уникальное поле
	 * 
	 * @param x Положение планеты на фрейме по x
	 * 
	 * @param y Положение планеты на фрейме по y
	 */
	
	public Planet(String name, String[] history, double weight,
			double age, double radius, int x, int y) {
		super(name, history, age, weight, (int)radius, (int)radius, x, y);
		
	}
	
	//Get&Set generated by eclipse
	
	public int getPop() {
		return pop;
	}
	public void setPop(int pop) {
		this.pop = pop;
	}
	public int getMaxPop() {
		return maxPop;
	}
	public void setMaxPop(int maxPop) {
		this.maxPop = maxPop;
	}
	
	private int pop;
	private int maxPop;
	
}
